openapi: 3.0.0
paths:
  /api/v1/health:
    get:
      operationId: HealthController_check
      summary: Get the health of the system
      description: Get the health of the system
      parameters: []
      responses:
        "200":
          description: The Health Check is successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  info:
                    type: object
                    example:
                      &a1
                      database:
                        &a2
                        status: up
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
                    nullable: true
                  error:
                    type: object
                    example: {}
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
                    nullable: true
                  details:
                    type: object
                    example: *a1
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
        "503":
          description: The Health Check is not successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  info:
                    type: object
                    example: *a1
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
                    nullable: true
                  error:
                    type: object
                    example:
                      redis:
                        &a3
                        status: down
                        message: Could not connect
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
                    nullable: true
                  details:
                    type: object
                    example:
                      database: *a2
                      redis: *a3
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
      tags:
        &a7
        - Health
  /api/v1/health/university-service:
    get:
      operationId: HealthController_checkUniversityService
      summary: Get the health of university service database
      description: Get the health of university service database
      parameters: []
      responses:
        "200":
          description: The Health Check is successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  info:
                    type: object
                    example:
                      &a4
                      database:
                        &a5
                        status: up
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
                    nullable: true
                  error:
                    type: object
                    example: {}
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
                    nullable: true
                  details:
                    type: object
                    example: *a4
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
        "503":
          description: The Health Check is not successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  info:
                    type: object
                    example: *a4
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
                    nullable: true
                  error:
                    type: object
                    example:
                      redis:
                        &a6
                        status: down
                        message: Could not connect
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
                    nullable: true
                  details:
                    type: object
                    example:
                      database: *a5
                      redis: *a6
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                      additionalProperties:
                        type: string
      tags: *a7
  /api/v1/subjects:
    post:
      operationId: SubjectsController_create
      summary: Create a new subject
      description: Create a new subject
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSubjectDto"
      responses:
        "201":
          description: The subject has been successfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateSubjectResponseDto"
        "500":
          description: Internal Server Error.
      tags:
        &a8
        - Subjects
      security:
        &a9
        - access-token: []
    get:
      operationId: SubjectsController_findAll
      summary: Find all subjects
      description: Find all subjects
      parameters:
        - name: order
          required: false
          in: query
          schema:
            default: ASC
            enum:
              - ASC
              - DESC
            type: string
        - name: page
          required: false
          in: query
          schema:
            minimum: 1
            default: 1
            type: number
        - name: take
          required: false
          in: query
          schema:
            minimum: 1
            maximum: 50
            default: 10
            type: number
      responses:
        "200":
          description: The subject has been found.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SubjectResponseDto"
      tags: *a8
      security: *a9
    delete:
      operationId: SubjectsController_removeAll
      summary: Delete all subjects
      description: Delete all subjects
      parameters: []
      responses:
        "200":
          description: The subjects have been deleted.
          content:
            application/json:
              schema:
                type: number
      tags: *a8
      security: *a9
  "/api/v1/subjects/{code}":
    get:
      operationId: SubjectsController_findOne
      summary: Find a subject by code
      description: Find a subject by code
      parameters:
        - name: code
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: The subject has been found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubjectResponseDto"
      tags: *a8
      security: *a9
    patch:
      operationId: SubjectsController_update
      summary: Update a subject by code
      description: Update a subject by code
      parameters:
        - name: code
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateSubjectDto"
      responses:
        "200":
          description: The subject has been updated.
          content:
            application/json:
              schema:
                type: number
      tags: *a8
      security: *a9
    delete:
      operationId: SubjectsController_remove
      summary: Delete a subject by code
      description: Delete a subject by code
      parameters:
        - name: code
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: The subject has been deleted.
          content:
            application/json:
              schema:
                type: number
      tags: *a8
      security: *a9
info:
  title: NestJS Security REST API
  description: Open University of Catalonia
  version: "1.0"
  contact: {}
tags: []
servers:
  - url: https://localhost:443
    description: null
    variables: null
components:
  securitySchemes:
    access-token:
      scheme: Bearer
      bearerFormat: Bearer
      type: http
      name: JWT
      description: Enter JWT token
      in: header
  schemas:
    CreateSubjectDto:
      type: object
      properties:
        academicalYear:
          type: string
        code:
          type: string
        lang:
          type: string
          enum:
            &a10
            - CAS
            - CAT
            - ANG
        name:
          type: string
        description:
          type: string
      required:
        - academicalYear
        - code
        - lang
        - name
        - description
    CreateSubjectResponseDto:
      type: object
      properties:
        id:
          type: string
      required:
        - id
    SubjectResponseDto:
      type: object
      properties:
        academicalYear:
          type: string
        code:
          type: string
        lang:
          type: string
          enum: *a10
        name:
          type: string
        description:
          type: string
        createdDate:
          format: date-time
          type: string
        updatedDate:
          format: date-time
          type: string
      required:
        - academicalYear
        - code
        - lang
        - name
        - description
        - createdDate
        - updatedDate
    UpdateSubjectDto:
      type: object
      properties:
        academicalYear:
          type: string
        code:
          type: string
        lang:
          type: string
          enum: *a10
        name:
          type: string
        description:
          type: string
