openapi: 3.0.0
paths:
  /api/v1:
    get:
      operationId: ApiGatewayController_getHello
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - Root
info:
  title: NestJS Security REST API
  description: Open University of Catalonia
  version: "1.0"
  contact: {}
tags: []
servers:
  - url: http://localhost:3000
    description: null
    variables: null
components:
  securitySchemes:
    bearer:
      scheme: Bearer
      bearerFormat: JWT
      type: http
      name: JWT
      description: Enter JWT token
      in: header
  schemas: {}
