openapi: 3.0.0
paths:
  /api/v1/subjects:
    post:
      operationId: SubjectsController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSubjectDto"
      responses:
        "201":
          description: ""
      tags:
        - Subjects
info:
  title: NestJS Security REST API
  description: Open University of Catalonia
  version: "1.0"
  contact: {}
tags: []
servers:
  - url: http://localhost:3000
    description: null
    variables: null
components:
  securitySchemes:
    bearer:
      scheme: Bearer
      bearerFormat: JWT
      type: http
      name: JWT
      description: Enter JWT token
      in: header
  schemas:
    CreateSubjectDto:
      type: object
      properties:
        academicalYear:
          type: string
        code:
          type: number
        lang:
          type: string
          enum:
            - CAS
            - CAT
            - ANG
        name:
          type: string
        description:
          type: string
      required:
        - academicalYear
        - code
        - lang
        - name
        - description
