### List all subjects
GET http://localhost:3001/subjects

### Create a new subject
POST http://localhost:3001/subjects
Content-Type: application/json

{
  "name": "maths",
  "code": "12345"
}

### Get a subject
GET http://localhost:3001/subjects/123456
