version: '3.9'
name: nestjs-security-rest-api-infra
services:
  uoc-database:
    image: 'postgres:${POSTGRES_VERSION:?err}'
    restart: always
    volumes:
      - ./initialize-uoc-database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      uocnetwork:
        aliases:
          - uoc-database
  uoc-api-gateway:
    command: node dist/main
    ports:
      - '${API_GATEWAY_PORT:?err}:${API_GATEWAY_PORT:?err}'
    restart: always
    networks:
      uocnetwork:
        aliases:
          - uoc-api-gateway

networks:
  uocnetwork:
