version: "3.9"
name: nestjs-security-rest-api-infra
services:
  uoc-database:
    image: "postgres:${POSTGRES_VERSION:?err}"
    restart: always
    volumes:
      - ./initialize-uoc-database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      uocnetwork:
        aliases:
          - uoc-database

  # uoc-backend:
  #   container_name: "uoc-backend-local"
  #   # TODO update command
  #   # command: node dist/apps/XYZ/main
  #   env_file:
  #     - ./.uoc-backend.env
  #   depends_on:
  #     uoc-database:
  #       condition: service_healthy
  #   networks:
  #     uocnetwork:
  #       aliases:
  #         - uoc-backend

networks:
  uocnetwork:
